manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nicell
      url-base: https://github.com/nicell
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: careyk007
      url-base: https://github.com/careyk007
  projects:
    - name: zmk
      remote: careyk007
      revision: main
      import: app/west.yml
  self:
    path: config
